import streamlit as st
from utils.common import load_data, apply_filters, inject_css

st.set_page_config(
    page_title="Global Air Pollution | AQI Intelligence",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded",
)

inject_css()

st.sidebar.title("🌍 AQI Intelligence")
st.sidebar.caption("Global Air Pollution — ML & Deep Learning")

df = load_data()

if df is None:
    st.title("🌍 Global Air Pollution")
    st.subheader("AQI Prediction with Machine Learning & Deep Learning")
    st.warning(
        "Dataset not found. Put `synthetic_global_air_pollution.csv` inside the "
        "`data/` folder and restart Streamlit."
    )
    st.markdown("""
### PyCharm project setup

1. Put the Kaggle CSV in `data/synthetic_global_air_pollution.csv`.
2. Put the model/preprocessing files generated by `train_models.py` in `models/`.
3. Install the packages from `requirements.txt`.
4. Run:

```bash
streamlit run app.py
```
""")
    st.stop()

st.sidebar.success(f"Dataset loaded: {len(df):,} rows")

filtered = apply_filters(df)

st.title("🌍 Global Air Pollution")
st.markdown(
    "### AQI Prediction & Air-Quality Intelligence Dashboard"
)
st.write(
    "Explore the dataset, understand pollution patterns, compare trained models, "
    "and generate AQI / AQI-category predictions using the same feature engineering "
    "workflow as the Kaggle notebook."
)

c1, c2, c3, c4 = st.columns(4)
c1.metric("Records", f"{len(df):,}")
c2.metric("Cities", f"{df['City'].nunique()}")
c3.metric("Countries", f"{df['Country'].nunique()}")
c4.metric("Average AQI", f"{df['AQI'].mean():.1f}")

st.divider()

left, right = st.columns([1.3, 1])

with left:
    st.subheader("AQI Overview")
    monthly = (
        filtered.assign(Date=filtered["Date"].dt.to_period("M").dt.to_timestamp())
        .groupby("Date")["AQI"].mean()
        .reset_index()
        .set_index("Date")
    )
    st.line_chart(monthly, y="AQI")

with right:
    st.subheader("AQI Categories")
    st.bar_chart(filtered["AQI_Category"].value_counts())

st.divider()
st.subheader("Quick Start")
a, b, c = st.columns(3)
with a:
    st.info("📊 **EDA**\n\nExplore AQI, pollutants, countries, seasons and correlations.")
with b:
    st.info("🤖 **Prediction**\n\nEnter environmental measurements and predict AQI.")
with c:
    st.info("📈 **Models**\n\nReview the regression/classification models from the notebook.")

st.caption(
    "Source workflow: Kaggle notebook `global-air-pollution-minhal(1).ipynb`. "
    "The dataset is synthetic."
)
